# Generated by Django 4.2.26 on 2025-11-26 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
